#!/bin/bash

while true; do
    databases=($(ls -F | grep / | sed 's|/$||'))

    if [[ ${#databases[@]} -eq 0 ]]; then
        echo "There Are No Databases Created"
	PS3="Choose Option [1-5]: "
        break
    else
        echo "Available Databases:"
        PS3="Enter the number of the database to drop (or ${#options[@]} to exit): "
        options=("${databases[@]}" "Exit")
        select selectedDbName in "${options[@]}"; do
            if [[ $selectedDbName == "Exit" ]]; then
                cd ..
                . ./main
            elif [[ -z $selectedDbName ]]; then
                echo "Invalid selection. Please choose a valid database number or 'Exit' to exit."
                continue
            fi

            read -p "Are You Sure You Want to Drop Database $selectedDbName? (y/n): " conf
            case $conf in
                [Yy])
                    rm -r "$selectedDbName"
                    echo "$selectedDbName Dropped Successfully"

                    # Update the options array after successful drop
                    databases=($(ls -F | grep / | sed 's|/$||'))
                    options=("${databases[@]}" "Exit")

                    
                    PS3="Enter the number of the database to drop (or ${#options[@]} to exit): "
                    break
                    ;;
                [Nn])
                    continue
                    ;;
                *)
                    echo "Invalid Choice"
                    ;;
            esac
        done
    fi
done

